In [17]:
import pandas as pd
import numpy as np

In [18]:
base_cartao = pd.read_csv('D:/cursos/curso-machine-learning/bases_dados/credit_card_clients.csv', header=1)
base_cartao

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,29998,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,29999,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,30000,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [19]:
base_cartao['BILL_TOTAL'] = base_cartao["BILL_AMT1"] + base_cartao["BILL_AMT2"] + base_cartao["BILL_AMT3"] + base_cartao["BILL_AMT4"] + base_cartao["BILL_AMT5"] + base_cartao["BILL_AMT6"]
base_cartao

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,BILL_TOTAL
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,689,0,0,0,0,1,7704
1,2,120000,2,2,2,26,-1,2,0,0,...,3455,3261,0,1000,1000,1000,0,2000,1,17077
2,3,90000,2,2,2,34,0,0,0,0,...,14948,15549,1518,1500,1000,1000,1000,5000,0,101653
3,4,50000,2,2,1,37,0,0,0,0,...,28959,29547,2000,2019,1200,1100,1069,1000,0,231334
4,5,50000,1,2,1,57,-1,0,-1,0,...,19146,19131,2000,36681,10000,9000,689,679,0,109339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000,1,3,1,39,0,0,0,0,...,31237,15980,8500,20000,5003,3047,5000,1000,0,725349
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,...,5190,0,1837,3526,8998,129,0,0,0,21182
29997,29998,30000,1,2,2,37,4,3,2,-1,...,20582,19357,0,0,22000,4200,2000,3100,1,70496
29998,29999,80000,1,3,1,41,1,-1,0,0,...,11855,48944,85900,3409,1178,1926,52964,1804,1,266611
29999,30000,50000,1,2,1,46,0,0,0,0,...,32428,15313,2078,1800,1430,1000,1000,1000,1,230874

In [20]:
x_cartao = base_cartao.iloc[:, [1,25]].values
x_cartao

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]], shape=(30000, 2))

In [21]:
from sklearn.preprocessing import StandardScaler
scaler_cartao = StandardScaler()
x_cartao = scaler_cartao.fit_transform(x_cartao)

In [22]:
from sklearn.cluster import KMeans

In [23]:
wcss = []
for i in range(1, 11):
    kmeans_cartao = KMeans(n_clusters=i, random_state=0)
    kmeans_cartao.fit(x_cartao)
    wcss.append(kmeans_cartao.inertia_)

In [24]:
wcss

[60000.00000000003,
 35197.834391257355,
 20128.202635623347,
 15892.249716910757,
 10708.603774943509,
 8604.404544864536,
 7684.904846136847,
 6593.001391781401,
 5669.721586002741,
 5055.083531903297]

In [25]:
import plotly.express as px
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [26]:
kmeans_cartao = KMeans(n_clusters=4, random_state=0)
rotulos = kmeans_cartao.fit_predict(x_cartao)

In [27]:
centroides = kmeans_cartao.cluster_centers_
centroides

array([[-0.8003573 , -0.21246214],
       [ 0.83229968,  2.26380772],
       [ 1.7262985 , -0.34629345],
       [ 0.26260158, -0.40715868]])

In [28]:
import plotly.graph_objects as go

In [29]:
grafico1 = px.scatter(x = x_cartao[:, 0], y = x_cartao[:, 1], color = rotulos)
grafico2 = px.scatter(x = centroides[:, 0], y = centroides[:, 1], size=[4, 4, 4, 4])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

In [30]:
lsita_clientes = np.column_stack((base_cartao, rotulos))
lsita_clientes

array([[     1,  20000,      2, ...,      1,   7704,      0],
       [     2, 120000,      2, ...,      1,  17077,      0],
       [     3,  90000,      2, ...,      0, 101653,      0],
       ...,
       [ 29998,  30000,      1, ...,      1,  70496,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 30000,  50000,      1, ...,      1, 230874,      0]],
      shape=(30000, 27))

In [31]:
lsita_clientes = lsita_clientes[lsita_clientes[:,26].argsort()]
lsita_clientes

array([[     8, 100000,      2, ...,      0,  13486,      0],
       [     6,  50000,      1, ...,      0, 238114,      0],
       [     5,  50000,      1, ...,      0, 109339,      0],
       ...,
       [ 14695, 200000,      2, ...,      1,  95217,      3],
       [ 29992, 210000,      1, ...,      1,  15000,      3],
       [ 29997, 150000,      1, ...,      0,  21182,      3]],
      shape=(30000, 27))

# Agora fazendo o agrupamento com mais atributos

In [32]:
base_cartao.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month', 'BILL_TOTAL'],
      dtype='object')

In [33]:
x_cartao_mais = base_cartao.iloc[:,[1,2,3,4,5,25]].values
x_cartao_mais

array([[ 20000,      2,      2,      1,     24,   7704],
       [120000,      2,      2,      2,     26,  17077],
       [ 90000,      2,      2,      2,     34, 101653],
       ...,
       [ 30000,      1,      2,      2,     37,  70496],
       [ 80000,      1,      3,      1,     41, 266611],
       [ 50000,      1,      2,      1,     46, 230874]], shape=(30000, 6))

In [ ]:
scaler_cartao_mais = StandardScaler()
x_cartao_mais = scaler_cartao_mais.fit_transform(x_cartao_mais)

In [35]:
x_cartao_mais

array([[-1.13672015,  0.81016074,  0.18582826, -1.05729503, -1.24601985,
        -0.69069198],
       [-0.3659805 ,  0.81016074,  0.18582826,  0.85855728, -1.02904717,
        -0.66599747],
       [-0.59720239,  0.81016074,  0.18582826,  0.85855728, -0.16115646,
        -0.44316987],
       ...,
       [-1.05964618, -1.23432296,  0.18582826,  0.85855728,  0.16430256,
        -0.52525745],
       [-0.67427636, -1.23432296,  1.45111372, -1.05729503,  0.59824792,
        -0.00856436],
       [-0.90549825, -1.23432296,  0.18582826, -1.05729503,  1.14067961,
        -0.10271861]], shape=(30000, 6))

In [37]:
wcss = []
for i in range(1,11):
    kmeans_cartao_mais = KMeans(n_clusters=i, random_state=0)
    kmeans_cartao_mais.fit(x_cartao_mais)
    wcss.append(kmeans_cartao_mais.inertia_)

In [38]:
grafico = px.line(x = range(1,11), y=wcss)
grafico.show()

In [49]:
kmeans_cartao_mais = KMeans(n_clusters=2, random_state=0)
rotulos = kmeans_cartao_mais.fit_predict(x_cartao_mais)

In [50]:
rotulos

array([0, 1, 1, ..., 1, 0, 0], shape=(30000,), dtype=int32)

In [52]:
from sklearn.decomposition import PCA

In [53]:
pca = PCA(n_components=2)
x_cartao_mais_pca = pca.fit_transform(x_cartao_mais)

In [54]:
x_cartao_mais_pca.shape

(30000, 2)

In [55]:
x_cartao_mais_pca

array([[-0.74082054, -1.13671858],
       [-1.48027121, -0.30100547],
       [-0.94737386, -0.48666789],
       ...,
       [-0.79468657, -0.90012663],
       [ 1.17562376, -1.54746987],
       [ 1.13614987, -1.14039836]], shape=(30000, 2))

In [56]:
grafico = px.scatter(x=x_cartao_mais_pca[:,0], y=x_cartao_mais_pca[:,1], color=rotulos)
grafico.show()

In [57]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:,26].argsort()]
lista_clientes

array([[ 30000,  50000,      1, ...,      1, 230874,      0],
       [ 29999,  80000,      1, ...,      1, 266611,      0],
       [ 29996, 220000,      1, ...,      0, 725349,      0],
       ...,
       [    21, 130000,      2, ...,      0, 123883,      1],
       [    20, 180000,      2, ...,      0,      0,      1],
       [    17,  20000,      1, ...,      1, 106161,      1]],
      shape=(30000, 27))