In [2]:
import pandas as pd
import numpy as np
from apyori import apriori

In [4]:
base_mercado1 = pd.read_csv('D:/cursos/curso-machine-learning/bases_dados/mercado.csv', header=None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [9]:
transacoes = []
for i in range(len(base_mercado1)):
    transacoes.append([str(base_mercado1.values[i, j]) for j in range(base_mercado1.shape[1])])

In [11]:
transacoes, type(transacoes)

([['leite', 'cerveja', 'pao', 'manteiga'],
  ['cafe', 'pao', 'manteiga', 'nan'],
  ['cafe', 'pao', 'manteiga', 'nan'],
  ['leite', 'cafe', 'pao', 'manteiga'],
  ['cerveja', 'nan', 'nan', 'nan'],
  ['manteiga', 'nan', 'nan', 'nan'],
  ['pao', 'nan', 'nan', 'nan'],
  ['feijao', 'nan', 'nan', 'nan'],
  ['arroz', 'feijao', 'nan', 'nan'],
  ['arroz', 'nan', 'nan', 'nan']],
 list)

In [17]:
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
resultados = list(regras)
resultados

[RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])]

In [18]:
len(resultados)

3

In [22]:
resultados[2]

RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

In [23]:
r = resultados[2][2]

In [24]:
r[0]

OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5)

In [25]:
r[2][0]

frozenset({'cafe', 'pao'})

In [38]:
lista_condicao = []
lista_resultado = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
    s = resultado[1]
    #print(s)
    result_rules = resultado[2]
    #print(result_rule)
    for result_rule in result_rules:
        #print(result_rule)  
        a = list(result_rule[0])
        b = list(result_rule[1])
        c = result_rule[2]
        l = result_rule[3]
        #print(a, ' - ', b, ' - ', c, ' - ', l)
        lista_condicao.append(a)
        lista_resultado.append(b)
        confianca.append(c)
        lift.append(l)
        suporte.append(s)

In [39]:
lista_condicao

[['cafe'], ['cafe'], ['cafe'], ['cafe', 'manteiga'], ['pao', 'cafe']]

In [40]:
lista_resultado

[['manteiga'], ['pao'], ['pao', 'manteiga'], ['pao'], ['manteiga']]

In [41]:
suporte

[0.3, 0.3, 0.3, 0.3, 0.3]

In [42]:
confianca

[1.0, 1.0, 1.0, 1.0, 1.0]

In [43]:
lift

[2.0, 2.0, 2.5, 2.0, 2.0]

In [44]:
rules_df = pd.DataFrame({'A': lista_condicao, 'B': lista_condicao, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

In [47]:
rules_df.sort_values(by = 'lift', ascending = False)

                  A                 B  suporte  confianca  lift
2            [cafe]            [cafe]      0.3        1.0   2.5
0            [cafe]            [cafe]      0.3        1.0   2.0
1            [cafe]            [cafe]      0.3        1.0   2.0
3  [cafe, manteiga]  [cafe, manteiga]      0.3        1.0   2.0
4       [pao, cafe]       [pao, cafe]      0.3        1.0   2.0